[project]
name = "imageprepare-for-qwenedit-outpaint"
version = "0.3.0"
description = "Prepare image/latent for Qwen Image Edit outpaint."

[tool.comfy]
PublisherId = "ALEXZ"
DisplayName = "ALEXZ_tools"
Icon = ""
